"use client";

import React, { useEffect, useState } from "react";
import { Layout } from "../../components/layout/Layout";
import { Card } from "../../components/ui/Card";
import { Badge } from "../../components/ui/Badge";
import { Button } from "../../components/ui/Button";
import { invoke } from "@tauri-apps/api/core";
import { Bell, CheckSquare, ShieldAlert, Coins, HelpCircle, Server } from "lucide-react";
import Link from "next/link";

interface Notification {
  id: string;
  type: string; // "failure" | "cost" | "system"
  severity: string; // "info" | "warning" | "error"
  workflow_id: string | null;
  run_id: string | null;
  title: string;
  body: string;
  sent_at: string;
  read_at: string | null;
}

export default function LogsPage() {
  const [notifications, setNotifications] = useState<Notification[]>([]);
  const [filter, setFilter] = useState<"all" | "failure" | "cost" | "system">("all");
  const [loading, setLoading] = useState(true);

  const fetchLogs = async () => {
    try {
      const list: Notification[] = await invoke("list_notifications");
      setNotifications(list);
      setLoading(false);
    } catch (e) {
      console.error(e);
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchLogs();
  }, []);

  const handleMarkAllRead = async () => {
    try {
      await invoke("mark_all_notifications_read");
      fetchLogs();
    } catch (e) {
      console.error(e);
    }
  };

  const filteredLogs = notifications.filter((log) => {
    if (filter === "all") return true;
    return log.type === filter;
  });

  const getLogIcon = (type: string) => {
    switch (type) {
      case "failure":
        return <ShieldAlert className="h-5 w-5 text-red-500" />;
      case "cost":
        return <Coins className="h-5 w-5 text-emerald-500" />;
      case "system":
      default:
        return <Server className="h-5 w-5 text-blue-500" />;
    }
  };

  const getSeverityBadge = (severity: string) => {
    switch (severity) {
      case "error":
        return <Badge variant="error">Critical</Badge>;
      case "warning":
        return <Badge variant="warn">Warning</Badge>;
      case "info":
      default:
        return <Badge variant="ok">Info</Badge>;
    }
  };

  return (
    <Layout title="Activity Logs">
      <div className="flex justify-between items-center mb-6">
        <div>
          <h2 className="text-base font-bold text-gray-900 dark:text-white">Notification & Activity Audit Logs</h2>
          <p className="text-xs text-gray-500 dark:text-gray-400">Review critical notices and alerts generated by execution engines</p>
        </div>
        <Button onClick={handleMarkAllRead} size="sm" className="flex items-center gap-1">
          <CheckSquare className="h-4 w-4" /> Mark All Read
        </Button>
      </div>

      {/* Filter Tabs */}
      <div className="flex border-b border-gray-250 dark:border-gray-800 mb-6 gap-6 text-xs font-semibold">
        <button
          onClick={() => setFilter("all")}
          className={`pb-2.5 border-b-2 border-none bg-transparent cursor-pointer ${
            filter === "all" ? "border-primary text-primary" : "border-transparent text-gray-500 hover:text-gray-800 dark:hover:text-gray-300"
          }`}
        >
          All Logs
        </button>
        <button
          onClick={() => setFilter("failure")}
          className={`pb-2.5 border-b-2 border-none bg-transparent cursor-pointer ${
            filter === "failure" ? "border-primary text-primary" : "border-transparent text-gray-500 hover:text-gray-800 dark:hover:text-gray-300"
          }`}
        >
          Failures
        </button>
        <button
          onClick={() => setFilter("cost")}
          className={`pb-2.5 border-b-2 border-none bg-transparent cursor-pointer ${
            filter === "cost" ? "border-primary text-primary" : "border-transparent text-gray-500 hover:text-gray-800 dark:hover:text-gray-300"
          }`}
        >
          Costs
        </button>
        <button
          onClick={() => setFilter("system")}
          className={`pb-2.5 border-b-2 border-none bg-transparent cursor-pointer ${
            filter === "system" ? "border-primary text-primary" : "border-transparent text-gray-500 hover:text-gray-800 dark:hover:text-gray-300"
          }`}
        >
          System
        </button>
      </div>

      {loading ? (
        <div className="flex items-center justify-center py-20">
          <div className="animate-spin h-8 w-8 border-4 border-primary border-t-transparent rounded-full" />
        </div>
      ) : filteredLogs.length === 0 ? (
        <Card className="empty-state max-w-md mx-auto">
          <div className="empty-state-icon">
            <Bell className="h-12 w-12 text-gray-300 dark:text-gray-700" />
          </div>
          <h4 className="text-sm font-semibold mb-1">No Activity Notices</h4>
          <p className="text-xs text-gray-500 mb-4">Your audit trails are fully clear. No recent alerts matching this filter.</p>
        </Card>
      ) : (
        <div className="space-y-3">
          {filteredLogs.map((log) => (
            <Card key={log.id} className={`p-4 hover:shadow-sm transition ${log.read_at ? "" : "border-l-4 border-l-primary"}`}>
              <div className="flex justify-between items-start gap-4">
                <div className="flex gap-3 items-start">
                  <div className="p-2 bg-gray-50 dark:bg-gray-900 rounded">{getLogIcon(log.type)}</div>
                  <div>
                    <h4 className="font-bold text-xs text-gray-950 dark:text-white flex items-center gap-2">
                      {log.title}
                      {!log.read_at && <span className="h-2 w-2 bg-primary rounded-full" />}
                    </h4>
                    <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">{log.body}</p>
                    <span className="text-[10px] text-gray-400 mt-2 block">
                      {new Date(log.sent_at).toLocaleString()}
                    </span>
                  </div>
                </div>

                <div className="flex items-center gap-3">
                  {getSeverityBadge(log.severity)}
                  {log.run_id && log.workflow_id && (
                    <Link
                      href={`/workflows/runs?workflowId=${log.workflow_id}&runId=${log.run_id}`}
                      className="btn btn-secondary btn-sm"
                    >
                      Inspect Execution
                    </Link>
                  )}
                </div>
              </div>
            </Card>
          ))}
        </div>
      )}
    </Layout>
  );
}
